FROM python:3.11-slim

# Устанавливаем iptables
RUN apt-get update && apt-get install -y iptables && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install fastapi uvicorn requests

COPY admin_backend.py .

EXPOSE 8003

CMD ["python", "-m", "uvicorn", "admin_backend:app", "--host", "0.0.0.0", "--port", "8003"]
